### ISSUE TITLE
[TODO]符号付き64bit整数の最小値を扱えるようにする

### ISSUE THREAD

**Issue by hide0123** [bomkei/newmetro#6]
- 現在の実装では符号付き64bit整数の最小値(-9223372036854775808)が扱えない（オーバーフロー判定になる）。
- 原因は、符号を含まない数値部分のみで判定しており、これが符号付き64bit整数の最大値(9223372036854775807)を超えてしまうため。

- 目標：以下の通り実行できるようにする。

```bash
$ cat test.txt
println(-9223372036854775808);
$ ./metro
-9223372036854775808
```

**Comment by bomkei** [comment]
実装済み
